export const charactersArr = [
    {name: 'Terje', 
      img: 'Terje.jpg', 
      ability: 'High-Pitch Singing',
      abilityText: 'Immune to distractions',
      strength: 60,
      speed: 50,
      intelligence: 70,
      wisdom: 60
    }, 
    {name: 'Magnus',
      img: 'Magnus.jpg',
      ability: 'Card Throw', 
      abilityText: 'Increased assembly speed', 
      strength: 90,
      speed: 60,
      intelligence: 50,
      wisdom: 40
    }, 
    {name: 'Kevin',
      img: 'Kevin.jpg',
      ability: 'Flying Carpet', 
      abilityText: 'Increased movement speed',
      strength: 50,
      speed: 80,
      intelligence: 60,
      wisdom: 50
    }, 
    {name: 'Ola',
      img: 'Ola.jpg',
      ability: 'Super Wash', 
      abilityText: 'Increased cleaning success rate', 
      strength: 60,
      speed: 70,
      intelligence: 50,
      wisdom: 60
    }, 
    {name: 'Svein',
      img: 'Svein.jpg',
      ability: 'Steady Rythm', 
      abilityText: 'Immune to mistakes', 
      strength: 50,
      speed: 40,
      intelligence: 60,
      wisdom: 90
    }, 
    {name: 'Bjørn',
      img: 'Bjørn.jpg',
      ability: 'Hyper Speed', 
      abilityText: 'Increased working speed', 
      strength: 40,
      speed: 90,
      intelligence: 50,
      wisdom: 60
    }, 
    {name: 'Ole Christian',
      img: 'OleChristian.jpg',
      ability: 'Story Teller', 
      abilityText: 'Increased wisdom', 
      strength: 50,
      speed: 80,
      intelligence: 50,
      wisdom: 60
    }, 
    {name: 'Hilde',
      img: 'Hilde.jpg',
      ability: 'Charming Smile', 
      abilityText: 'Increased charisma', 
      strength: 50,
      speed: 50,
      intelligence: 70,
      wisdom: 70
    }, 
    {name: 'Andreas',
      img: 'Andreas.jpg',
      ability: 'Wolf Companion', 
      abilityText: 'Increased work success rate', 
      strength: 80,
      speed: 70,
      intelligence: 40,
      wisdom: 50
    }, 
    {name: 'Ole Jakob',
      img: 'OleJakob.jpg',
      ability: 'Funny Joke', 
      abilityText: 'Increased charisma', 
      strength: 70,
      speed: 70,
      intelligence: 50,
      wisdom: 50
    }
    ]